### ISSUE TITLE
undocumented ENV vars

### ISSUE THREAD

**Issue by gartl1337** [mwaeckerlin/openldap#16]
Hi,

I've just tried to pull your image from docker hub and noticed a lot of different undocumented variables like:
ALLOW_USER=chown -R sombody:somebody
USER=ldap
RUN_USER=somebody
RUN_HOME=/home/somebody
RUN_GROUP=somebody
WWWUSER=nginx

I'm really confused, if I can delete them or if I should set them?

EDIT: I'm using cloudjiffy.co as docker hoster, maybe they're running a configuration, which conflicts with your image?

BR

**Comment by mwaeckerlin** [comment]
These variables are used internally, i.e. during the build process. Most are inherited from `mwaeckerlin/base` and the same exist in `mwaeckerlin/ubuntu-base`. One reason for them is to abstract distribution dependent stuff, that's why there is also a `PKG_INSTALL` and `PKG_REMOVE`. They help me to keep the different images consistent and to reduce the amount of changes when switching to another distribution.

They are not meant to be set when using the image. That's why they are not documented in the `README.md`.
